// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.Data;

#nullable disable

namespace app.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250707174913_add-item-table-mrigation")]
    partial class additemtablemrigation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("app.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameItem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuantityItem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_Item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameItem = "Product 1",
                            QuantityItem = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
