// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.Data;

#nullable disable

namespace app.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260113205616_Logs_Config")]
    partial class Logs_Config
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("app.Models.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameConfig")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ValueConfig")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TB_Config");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameConfig = "endTime",
                            ValueConfig = "20:00"
                        },
                        new
                        {
                            Id = 2,
                            NameConfig = "accelerometer",
                            ValueConfig = "60"
                        },
                        new
                        {
                            Id = 3,
                            NameConfig = "intentoryTime",
                            ValueConfig = "60"
                        },
                        new
                        {
                            Id = 4,
                            NameConfig = "initialTime",
                            ValueConfig = "09:00"
                        },
                        new
                        {
                            Id = 5,
                            NameConfig = "byDay",
                            ValueConfig = "0"
                        },
                        new
                        {
                            Id = 6,
                            NameConfig = "finalDay",
                            ValueConfig = ""
                        },
                        new
                        {
                            Id = 7,
                            NameConfig = "inventoryBy10",
                            ValueConfig = "0"
                        },
                        new
                        {
                            Id = 8,
                            NameConfig = "prizeBy10",
                            ValueConfig = "5"
                        });
                });

            modelBuilder.Entity("app.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameItem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuantityItem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_Item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameItem = "Product 1",
                            QuantityItem = 8
                        });
                });

            modelBuilder.Entity("app.Models.Logs_Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataInventoryCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DistributedInTen")
                        .HasColumnType("int");

                    b.Property<string>("DistributionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DividedDay")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemsQuantity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SpeedDistribution")
                        .HasColumnType("longtext");

                    b.Property<string>("TimeInterval")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TB_Logs_Config");
                });

            modelBuilder.Entity("app.Models.Logs_Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CurrentInventory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DataInventoryCreated")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TB_Logs_Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
